# Generated by Django 5.1.7 on 2025-04-03 02:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bug_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier extracted from email subject (e.g., BUG-1234)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Full subject line from the email", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Content from the email body"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the bug was first created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the bug was last updated",
                    ),
                ),
                (
                    "modified_count",
                    models.IntegerField(
                        default=0,
                        help_text="Counter incremented each time the bug is updated via email",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the email",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the email was sent"
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Email address of the recipient", max_length=255
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject line of the email", max_length=255
                    ),
                ),
                ("body", models.TextField(help_text="Content of the email")),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique Message-ID header from the processed email",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the email was processed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processed Email Record",
                "verbose_name_plural": "Processed Email Records",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="BugModificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp of the specific modification event",
                    ),
                ),
                (
                    "bug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modification_logs",
                        to="api.bug",
                    ),
                ),
            ],
            options={
                "ordering": ["-modified_at"],
            },
        ),
    ]
