# Generated by Django 5.1.7 on 2025-04-03 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailLog",
        ),
        migrations.AlterField(
            model_name="bug",
            name="bug_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique identifier (e.g., BUG-1234)",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="bug",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="bug",
            name="description",
            field=models.TextField(help_text="Email body content"),
        ),
        migrations.AlterField(
            model_name="bug",
            name="modified_count",
            field=models.IntegerField(
                default=0, help_text="Incremented on email updates"
            ),
        ),
        migrations.AlterField(
            model_name="bug",
            name="subject",
            field=models.CharField(help_text="Full subject line", max_length=255),
        ),
        migrations.AlterField(
            model_name="bug",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="bugmodificationlog",
            name="modified_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp of modification event",
            ),
        ),
        migrations.AlterField(
            model_name="processedemail",
            name="message_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique Message-ID header",
                max_length=500,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="processedemail",
            name="processed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
