# Generated by Django 5.1.7 on 2025-03-30 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bug",
            options={"ordering": ["-last_email_received_at", "-created_at"]},
        ),
        migrations.RenameField(
            model_name="bug",
            old_name="updated_at",
            new_name="last_manual_update_at",
        ),
        migrations.RemoveField(
            model_name="bug",
            name="subject",
        ),
        migrations.AddField(
            model_name="bug",
            name="last_email_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bug",
            name="latest_subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bug",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bug",
            name="unique_id",
            field=models.CharField(
                db_index=True,
                help_text="The unique identifier extracted from the email subject.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("email_subject", models.CharField(max_length=255)),
                (
                    "parsed_priority",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "parsed_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("parsed_description", models.TextField(blank=True, null=True)),
                (
                    "parsed_assignee",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="api.bug",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
    ]
